# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml

controller:
  admin:
    existingSecret: jenkins
  serviceType: NodePort
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 4096Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: ci.dev.compliantcloud.com
    paths:
      - backend:
          service:
            name: jenkins
            port: 
              number: 8080
        path: /
        pathType: ImplementationSpecific
    tls:
      - secretName: ci.dev.compliantcloud.com
        hosts:
          - ci.dev.compliantcloud.com
  installPlugins:
    - kubernetes:4358.vcfd9c5a_0a_f51
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.7.0
    - configuration-as-code:1985.vdda_32d0c4ea_b_
  # nodeSelector:
  #   kubernetes.io/os: linux
  # tolerations:
  #   - key: CriticalAddonsOnly
  #     operator: Exists
  #   - key: node-role.kubernetes.io/master
  #     effect: NoSchedule
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: node-role.kubernetes.io/control-plane
  #               operator: Exists