controller:
  serviceType: NodePort
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 4096Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: ci.dev.compliantcloud.com
    paths:
      - backend:
          service:
            name: jenkins
            port: 
              number: 8080
        path: /
        pathType: ImplementationSpecific
    tls:
      - secretName: ci.dev.compliantcloud.com
        hosts:
          - ci.dev.compliantcloud.com
  # nodeSelector:
  #   kubernetes.io/os: linux
  # tolerations:
  #   - key: CriticalAddonsOnly
  #     operator: Exists
  #   - key: node-role.kubernetes.io/master
  #     effect: NoSchedule
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: node-role.kubernetes.io/control-plane
  #               operator: Exists